// Where the site is deployed. In production set NUXT_PUBLIC_SITE_URL to the origin
// (e.g. https://example.com) and NUXT_APP_BASE_URL if it is served from a sub-path, so
// canonical links, Open Graph tags, JSON-LD, the sitemap and robots.txt use the real address.
const siteOrigin = (process.env.NUXT_PUBLIC_SITE_URL || 'http://localhost:3000').replace(/\/$/, '')
const siteUrl = siteOrigin + (process.env.NUXT_APP_BASE_URL || '/').replace(/\/$/, '')

export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',

  app: {
    head: {
      title: "ProjectFlow",
      meta: [
        { name: "description", content: "ProjectFlow project and task management system" },
        { name: "viewport", content: "width=device-width, initial-scale=1" },
        { property: "og:site_name", content: "ProjectFlow" },
        { property: "og:type", content: "website" },
        { name: "twitter:card", content: "summary_large_image" }
      ],
      // Point at the favicon under the base path, so it also loads when served from a sub-path
      link: [
        { rel: "icon", type: "image/x-icon", href: `${process.env.NUXT_APP_BASE_URL || '/'}favicon.ico` }
      ]
    }
  },

  runtimeConfig: {
    public: {
      appUrl: siteUrl
    }
  },

  modules: [
    '@pinia/nuxt',
    '@nuxtjs/tailwindcss',
    '@nuxtjs/sitemap'
  ],

  // Used by @nuxtjs/sitemap; it adds app.baseURL itself, so pass only the origin
  site: {
    url: siteOrigin,
    name: 'ProjectFlow'
  },

  // robots.txt is generated by server/routes/robots.txt.ts so it uses siteUrl too
  nitro: {
    prerender: {
      routes: ['/robots.txt']
    }
  }
})
